# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{i18n_generators}
  s.version = "0.8.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Akira Matsuda"]
  s.date = %q{2010-10-23}
  s.description = %q{A Rails generator plugin & gem that generates Rails 2.2 and 2.3 I18n locale files for almost every known locale.}
  s.email = %q{ronnie@dio.jp}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "generators/i18n/USAGE",
     "generators/i18n/i18n_generator.rb",
     "generators/i18n/lib/yaml.rb",
     "generators/i18n/templates/base.yml",
     "generators/i18n/templates/i18n_config.rb",
     "generators/i18n/templates/translation.yml",
     "generators/i18n_locale/USAGE",
     "generators/i18n_locale/i18n_locale_command.rb",
     "generators/i18n_locale/i18n_locale_generator.rb",
     "generators/i18n_locale/lib/cldr.rb",
     "generators/i18n_scaffold/i18n_scaffold_generator.rb",
     "generators/i18n_scaffold/templates/controller.rb",
     "generators/i18n_scaffold/templates/functional_test.rb",
     "generators/i18n_scaffold/templates/helper.rb",
     "generators/i18n_scaffold/templates/helper_test.rb",
     "generators/i18n_scaffold/templates/layout.html.erb",
     "generators/i18n_scaffold/templates/style.css",
     "generators/i18n_scaffold/templates/view_edit.html.erb",
     "generators/i18n_scaffold/templates/view_index.html.erb",
     "generators/i18n_scaffold/templates/view_new.html.erb",
     "generators/i18n_scaffold/templates/view_show.html.erb",
     "generators/i18n_translation/USAGE",
     "generators/i18n_translation/i18n_translation_command.rb",
     "generators/i18n_translation/i18n_translation_generator.rb",
     "generators/i18n_translation/lib/erb_executer.rb",
     "generators/i18n_translation/lib/recording_backend.rb",
     "generators/i18n_translation/lib/through_ryoku.rb",
     "generators/i18n_translation/lib/translator.rb",
     "i18n_generators.gemspec",
     "spec/cldr_spec.rb",
     "spec/data/cldr/ja.html",
     "spec/data/yml/active_record/en-US.yml",
     "spec/i18n_locale_command_spec.rb",
     "spec/i18n_translation_command_spec.rb",
     "spec/spec_helper.rb",
     "spec/translator_spec.rb",
     "spec/yaml_spec.rb"
  ]
  s.homepage = %q{http://github.com/amatsuda/i18n_generators/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Generates I18n locale files for Rails 2.2 and 2.3}
  s.test_files = [
    "spec/cldr_spec.rb",
     "spec/i18n_locale_command_spec.rb",
     "spec/i18n_translation_command_spec.rb",
     "spec/spec_helper.rb",
     "spec/translator_spec.rb",
     "spec/yaml_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

